name: 'Terraform tests'

on:
  push:
  workflow_dispatch:

permissions:
  # required for all workflows
  security-events: write

  # only required for workflows in private repositories
  actions: read
  contents: write

jobs:
  TF_Tests:
    name: Terraform Tests
    uses: otc-code/gh-workflows/.github/workflows/tf_test.yml@main


