name: 'Terraform tests'

on:
  push:
  workflow_dispatch:

permissions:
  security-events: write
  contents: write
jobs:
  TF_Tests:
    name: Terraform Tests
    uses: otc-code/gh-workflows/.github/workflows/tf_test.yml@main


